import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import './carDealership.css';

const vehicles = [
  { id: 'audi-rs6', name: 'Audi RS 6 Avant', type: 'Luxury', year: 2025, price: 129900, mileage: '2,480 mi', fuel: 'Petrol', transmission: 'Automatic', engine: '4.0L V8', badge: 'New arrival', image: 'photo-1606664515524-ed2f786a0bd6', features: ['Panoramic glass roof', 'Bang & Olufsen sound', 'Matrix LED headlights', 'RS sport exhaust'] },
  { id: 'bmw-x5', name: 'BMW X5 xDrive40i', type: 'SUV', year: 2024, price: 78500, mileage: '8,120 mi', fuel: 'Hybrid', transmission: 'Automatic', engine: '3.0L Turbo', badge: 'Featured', image: 'photo-1555215695-3004980ad54e', features: ['M Sport package', 'Heated leather interior', '360° parking camera', 'Adaptive cruise control'] },
  { id: 'ford-f150', name: 'Ford F-150 Lariat', type: 'Pickup', year: 2023, price: 58900, mileage: '14,600 mi', fuel: 'Petrol', transmission: 'Automatic', engine: '3.5L EcoBoost', badge: 'Low mileage', image: 'photo-1592805723127-004c85d0b3b0', features: ['Pro Power Onboard', 'B&O audio system', 'Tow package', '360° camera'] },
  { id: 'tesla-model-s', name: 'Tesla Model S Plaid', type: 'Electric', year: 2024, price: 94900, mileage: '3,210 mi', fuel: 'Electric', transmission: 'Automatic', engine: '1,020 hp', badge: 'Electric', image: 'photo-1560958089-b8a1929cea89', features: ['Tri-motor AWD', 'Glass roof', 'Autopilot', 'Premium connectivity'] },
  { id: 'porsche-911', name: 'Porsche 911 Carrera', type: 'Luxury', year: 2022, price: 118500, mileage: '6,700 mi', fuel: 'Petrol', transmission: 'Automatic', engine: '3.0L Flat-6', badge: 'Certified', image: 'photo-1503376780353-7e6692767b70', features: ['Sport Chrono package', 'Bose surround sound', 'Adaptive sport seats', 'Porsche Active Suspension'] },
  { id: 'mercedes-c-class', name: 'Mercedes-Benz C 300', type: 'Sedan', year: 2024, price: 52400, mileage: '5,890 mi', fuel: 'Hybrid', transmission: 'Automatic', engine: '2.0L Turbo', badge: 'Popular', image: 'photo-1618843479313-40f8afb4b4d8', features: ['Burmester 3D sound', 'Ambient lighting', 'Driver assistance', 'Heated front seats'] },
];

const imageUrl = (id, width = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const money = (price) => `$${price.toLocaleString()}`;

function CarNav({ wishlistCount, compareCount }) {
  const [open, setOpen] = useState(false);
  return <header className="auto-nav"><div className="auto-nav-inner"><Link to="/demos/car-dealership" className="auto-logo"><span>V</span><strong>VELOCITY <em>MOTORS</em></strong></Link><button className="auto-menu" type="button" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><i /><i /><i /></button><nav className={open ? 'open' : ''}><a href="#inventory" onClick={() => setOpen(false)}>Inventory</a><a href="#services" onClick={() => setOpen(false)}>Services</a><a href="#finance" onClick={() => setOpen(false)}>Finance</a><a href="#contact" onClick={() => setOpen(false)}>Contact</a><a className="nav-counter" href="#inventory">♡ {wishlistCount}</a><a className="nav-counter" href="#compare">⇄ {compareCount}</a><a className="nav-cta" href="#test-drive" onClick={() => setOpen(false)}>Book a test drive <span>↗</span></a></nav></div></header>;
}

function VehicleCard({ vehicle, wished, compared, onWish, onCompare }) {
  return <article className="vehicle-card"><div className="vehicle-image" style={{ backgroundImage: `url(${imageUrl(vehicle.image)})` }}><span className="vehicle-badge">{vehicle.badge}</span><button className={`heart ${wished ? 'active' : ''}`} type="button" onClick={() => onWish(vehicle.id)} aria-label="Add to wishlist">{wished ? '♥' : '♡'}</button><div className="vehicle-type">{vehicle.type}</div></div><div className="vehicle-card-body"><div className="vehicle-heading"><div><span className="vehicle-year">{vehicle.year} / {vehicle.mileage}</span><h3>{vehicle.name}</h3></div><strong>{money(vehicle.price)}</strong></div><div className="vehicle-specs"><span>◉ {vehicle.fuel}</span><span>⇄ {vehicle.transmission}</span><span>⚙ {vehicle.engine}</span></div><div className="vehicle-actions"><Link to={`/demos/car-dealership/vehicle/${vehicle.id}`}>View details <span>↗</span></Link><button type="button" className={compared ? 'compare active' : 'compare'} onClick={() => onCompare(vehicle.id)}>{compared ? '✓ Comparing' : '＋ Compare'}</button></div></div></article>;
}

function SearchPanel({ filters, setFilters, onSearch }) {
  return <form className="search-panel" onSubmit={(event) => { event.preventDefault(); onSearch(); }}><div className="search-title"><span>01</span><div><strong>Find your vehicle</strong><small>Search our current collection</small></div></div><label>Make<select value={filters.make} onChange={(event) => setFilters({ ...filters, make: event.target.value })}><option>All makes</option><option>Audi</option><option>BMW</option><option>Ford</option><option>Mercedes-Benz</option><option>Porsche</option><option>Tesla</option></select></label><label>Model<select value={filters.model} onChange={(event) => setFilters({ ...filters, model: event.target.value })}><option>All models</option><option>RS 6 Avant</option><option>X5</option><option>F-150</option><option>Model S</option><option>911</option></select></label><label>Year<select value={filters.year} onChange={(event) => setFilters({ ...filters, year: event.target.value })}><option>Any year</option><option>2025</option><option>2024</option><option>2023</option><option>2022</option></select></label><label>Fuel type<select value={filters.fuel} onChange={(event) => setFilters({ ...filters, fuel: event.target.value })}><option>Any fuel</option><option>Petrol</option><option>Hybrid</option><option>Electric</option></select></label><label>Transmission<select value={filters.transmission} onChange={(event) => setFilters({ ...filters, transmission: event.target.value })}><option>Any transmission</option><option>Automatic</option><option>Manual</option></select></label><label>Price range<select value={filters.price} onChange={(event) => setFilters({ ...filters, price: event.target.value })}><option>Any price</option><option>Under $60k</option><option>$60k – $100k</option><option>Over $100k</option></select></label><button className="search-submit" type="submit">Search inventory <span>→</span></button></form>;
}

function Home({ wished, compared, onWish, onCompare }) {
  const [filters, setFilters] = useState({ make: 'All makes', model: 'All models', year: 'Any year', fuel: 'Any fuel', transmission: 'Any transmission', price: 'Any price' });
  const [category, setCategory] = useState('All');
  const filtered = useMemo(() => vehicles.filter((vehicle) => (category === 'All' || vehicle.type === category) && (filters.year === 'Any year' || String(vehicle.year) === filters.year) && (filters.fuel === 'Any fuel' || vehicle.fuel === filters.fuel) && (filters.transmission === 'Any transmission' || vehicle.transmission === filters.transmission) && (filters.price === 'Any price' || (filters.price === 'Under $60k' && vehicle.price < 60000) || (filters.price === '$60k – $100k' && vehicle.price >= 60000 && vehicle.price <= 100000) || (filters.price === 'Over $100k' && vehicle.price > 100000))), [category, filters]);
  return <>
    <section className="auto-hero"><div className="hero-image" /><div className="hero-shade" /><div className="hero-content"><p className="auto-eyebrow"><span /> Velocity Motors / Est. 1998</p><h1>Drive your<br /><em>next journey.</em></h1><p className="hero-subtitle">A better way to buy a car. Curated vehicles, clear pricing and a team that knows the road ahead.</p><div className="hero-actions"><a className="auto-button blue" href="#inventory">Browse inventory <span>↗</span></a><a className="hero-text-link" href="#test-drive">Book a test drive <span>→</span></a></div></div><div className="hero-scroll">Scroll to explore <span>↓</span></div><SearchPanel filters={filters} setFilters={setFilters} onSearch={() => document.getElementById('inventory')?.scrollIntoView({ behavior: 'smooth' })} /></section>
    <section className="trust-strip"><div><strong>25+</strong><span>years on the road</span></div><div><strong>500+</strong><span>vehicles delivered</span></div><div><strong>4.9/5</strong><span>customer rating</span></div><div><strong>3 year</strong><span>vehicle warranty</span></div></section>
    <section id="inventory" className="auto-section inventory-section"><div className="section-top"><div><p className="auto-eyebrow dark">Our collection</p><h2>Find the one.</h2><p>Every vehicle inspected, prepared and ready for wherever life takes you.</p></div><a className="outline-link" href="#contact">Need help choosing? <span>↗</span></a></div><div className="category-tabs">{['All', 'SUV', 'Sedan', 'Pickup', 'Luxury', 'Electric'].map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)} type="button">{item}</button>)}</div><div className="inventory-count"><span>{filtered.length} vehicles found</span><span>Sorted by <b>featured</b>⌄</span></div><div className="vehicle-grid">{filtered.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} wished={wished.includes(vehicle.id)} compared={compared.includes(vehicle.id)} onWish={onWish} onCompare={onCompare} />)}</div>{filtered.length === 0 && <div className="empty-state">No vehicles match those filters. Try broadening your search.</div>}</section>
    <section className="statement-section"><div><p className="auto-eyebrow">The Velocity standard</p><h2>More than a car.<br /><em>A feeling.</em></h2></div><p>We believe buying a vehicle should feel as good as driving it. That means no pressure, no jargon, and no second guessing. Just exceptional cars and a better way forward.</p></section>
    <section id="services" className="auto-section collections-section"><div className="section-top"><div><p className="auto-eyebrow dark">Explore more</p><h2>Built for every road.</h2></div></div><div className="collection-grid"><a className="collection-card suv" href="#inventory"><span>01 / Collection</span><h3>SUVs &<br />crossovers</h3><b>Explore collection →</b></a><a className="collection-card electric" href="#inventory"><span>02 / Collection</span><h3>The electric<br />future</h3><b>Explore collection →</b></a><a className="collection-card finance" href="#finance"><span>03 / Service</span><h3>Finance<br />made clear</h3><b>Learn more →</b></a></div></section>
    <section id="compare" className="tools-section"><div className="auto-section"><div className="section-top"><div><p className="auto-eyebrow dark">Ownership, simplified</p><h2>Your next move.</h2></div><span className="tool-count">{compared.length} vehicles selected</span></div><div className="tools-grid"><article><span className="tool-icon">⇄</span><h3>Compare vehicles</h3><p>Put your shortlist side by side and make a confident choice.</p><a href="#inventory">{compared.length ? 'Review comparison' : 'Add vehicles to compare'} →</a></article><article><span className="tool-icon">↗</span><h3>Value your trade-in</h3><p>Get a fair estimate for your current car in a few simple steps.</p><a href="#contact">Start a trade-in enquiry →</a></article><article><span className="tool-icon">⚙</span><h3>Book a service</h3><p>Keep your vehicle performing at its best with our workshop team.</p><a href="#contact">Schedule a service →</a></article><article><span className="tool-icon">◷</span><h3>Recently viewed</h3><p>{wished.length ? `${wished.length} vehicle${wished.length > 1 ? 's' : ''} saved to your wishlist.` : 'Your recently viewed vehicles will appear here.'}</p><a href="#inventory">Browse inventory →</a></article></div></div></section>
    <section id="finance" className="finance-section"><div><p className="auto-eyebrow">Your next move</p><h2>Drive now.<br /><em>Pay your way.</em></h2><p>Flexible finance plans shaped around your life, your budget and the vehicle you want. Get a personalised estimate in minutes.</p><a className="auto-button blue" href="#contact">Explore finance <span>↗</span></a></div><div className="finance-card"><span>Monthly estimate</span><strong>From $649<small>/ month</small></strong><div className="finance-line"><i /><i /><i /><i /><i /></div><p>Based on a 60-month term<br />10% down payment · 7.2% APR</p><a href="#contact">Calculate your payment →</a></div></section>
    <section className="review-section"><div className="auto-section"><p className="auto-eyebrow dark">The word on the street</p><h2>Good journeys<br /><em>start here.</em></h2><div className="review-grid"><blockquote>“From the first message to picking up the keys, Velocity made everything feel effortless. I found exactly what I wanted.”<footer><strong>Marcus T.</strong><span>Verified buyer / BMW X5</span></footer></blockquote><blockquote>“The clearest, most honest car buying experience I’ve ever had. And the car is incredible.”<footer><strong>Sarah J.</strong><span>Verified buyer / Tesla Model S</span></footer></blockquote></div></div></section>
    <section id="contact" className="contact-section"><div><p className="auto-eyebrow dark">Come say hello</p><h2>Ready when<br />you are.</h2><p>Visit our showroom, speak with a specialist or start your journey online.</p><div className="contact-links"><a href="tel:+1555019898">+1 555 019 898 <span>↗</span></a><a href="mailto:hello@velocitymotors.com">hello@velocitymotors.com <span>↗</span></a></div></div><div className="map-placeholder"><span className="map-grid" /><div className="map-label"><strong>Velocity Motors</strong><span>200 Motorway Drive<br />Riverside District</span><a href="#test-drive">Get directions ↗</a></div></div></section>
  </>;
}

function Detail({ vehicle, wished, onWish }) {
  return <main className="detail-page"><Link className="back-link" to="/demos/car-dealership">← Back to inventory</Link><div className="detail-hero"><div className="detail-gallery"><div className="detail-main-image" style={{ backgroundImage: `url(${imageUrl(vehicle.image, 1600)})` }} /><div className="gallery-thumbs"><span style={{ backgroundImage: `url(${imageUrl(vehicle.image, 500)})` }} /><span style={{ backgroundImage: `url(${imageUrl('photo-1542282088-72c9c27ed0cd', 500)})` }} /><span style={{ backgroundImage: `url(${imageUrl('photo-1511919884226-fd3cad34687c', 500)})` }} /></div></div><div className="detail-copy"><span className="vehicle-badge">{vehicle.badge}</span><p className="vehicle-year">{vehicle.year} / {vehicle.mileage}</p><h1>{vehicle.name}</h1><strong className="detail-price">{money(vehicle.price)}</strong><p className="detail-intro">A beautifully presented example, inspected by our technicians and ready for its next chapter.</p><button className="auto-button blue" type="button" onClick={() => onWish(vehicle.id)}>{wished.includes(vehicle.id) ? '♥ Saved to wishlist' : '♡ Save to wishlist'}</button><a className="detail-drive" href="#test-drive">Book a test drive <span>↗</span></a><div className="detail-spec-grid"><div><span>Fuel type</span><strong>{vehicle.fuel}</strong></div><div><span>Transmission</span><strong>{vehicle.transmission}</strong></div><div><span>Engine</span><strong>{vehicle.engine}</strong></div><div><span>Exterior</span><strong>Metallic black</strong></div></div></div></div><section className="detail-lower"><div><p className="auto-eyebrow dark">Vehicle overview</p><h2>Everything<br /><em>in the detail.</em></h2><p>This {vehicle.year} {vehicle.name} combines everyday confidence with the kind of performance that makes a longer route worth taking.</p></div><div className="features-panel"><h3>Highlights & features</h3>{vehicle.features.map((feature) => <div key={feature}><span>✓</span>{feature}</div>)}<h3 className="safety-heading">Safety & assistance</h3><p>Lane keeping assist · Blind spot monitoring · Automatic emergency braking · 360° parking camera</p></div></section><section id="test-drive" className="enquiry-panel"><div><p className="auto-eyebrow">Take the wheel</p><h2>See how it<br /><em>feels.</em></h2><p>Book a private test drive or ask our team a question about this vehicle.</p></div><form onSubmit={(event) => event.preventDefault()}><input required placeholder="Your name" /><input required type="email" placeholder="Email address" /><input placeholder="Preferred date" type="date" /><textarea placeholder="Tell us how we can help" /><button className="auto-button blue" type="submit">Send enquiry <span>↗</span></button></form></section></main>;
}

function CarDealershipPage() {
  const { vehicleId } = useParams();
  const [wished, setWished] = useState([]);
  const [compared, setCompared] = useState([]);
  const vehicle = vehicles.find((item) => item.id === vehicleId);
  const toggle = (setter, id) => setter((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <div className="auto-shell"><CarNav wishlistCount={wished.length} compareCount={compared.length} />{vehicleId && vehicle ? <Detail vehicle={vehicle} wished={wished} onWish={(id) => toggle(setWished, id)} /> : <Home wished={wished} compared={compared} onWish={(id) => toggle(setWished, id)} onCompare={(id) => toggle(setCompared, id)} />}<footer className="auto-footer"><div className="auto-footer-brand"><span>V</span><strong>VELOCITY <em>MOTORS</em></strong></div><div><a href="#inventory">Inventory</a><a href="#finance">Finance</a><a href="#contact">Contact</a></div><p>This website is a demonstration created by ApexCole Technology. Every client website is uniquely designed around their business, brand and vision.</p></footer></div>;
}

export default CarDealershipPage;
